"""Synthesise every sound effect in the game, from nothing.

    python tools/audio-render/make_sounds.py --write

Writes 16-bit mono WAVs at 44.1 kHz into assets/audio/. Without --write it renders and
reports but leaves the files alone, which is the quick way to check nothing has drifted.

Why synthesised rather than sourced: everything else in this repository that is not code
is generated by a committed tool — the die frames, the README images — and audio has the
same problem those had. A generated sound has a provenance story of one line, can be
re-tuned by editing a number instead of re-recording, and cannot quietly acquire a licence
nobody read.

A die clack is modal synthesis: a short noise transient for the strike, plus a handful of
exponentially decaying partials at inharmonic ratios for the body ringing. That is how the
real thing works — a small hard object has a few strong modes and no harmonic series — and
it is why these do not sound like beeps.
"""

import argparse
import os
import zlib
import sys
import wave

import numpy as np

SR = 44100
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "assets", "audio")

rng = np.random.default_rng(20260821)      # fixed: two runs give identical files


def t(dur):
    return np.arange(int(SR * dur)) / SR


def decay(times, tau):
    """Exponential decay. tau is the time to fall to 1/e."""
    return np.exp(-times / tau)


def partial(times, freq, tau, amp=1.0, phase=0.0):
    return amp * np.sin(2 * np.pi * freq * times + phase) * decay(times, tau)


def noise(times, tau, lo=None, hi=None):
    n = rng.normal(0.0, 1.0, len(times))
    if lo or hi:
        n = band(n, lo, hi)
    return n * decay(times, tau)


def band(x, lo=None, hi=None, order=4):
    """Band-limit in the frequency domain.

    A one-pole was the first attempt and it is not enough: at 6 dB/octave a "lowpassed"
    noise burst is still mostly hiss, and every sound came out with a spectral centroid
    near 6 kHz whatever its modes were. Shaping the spectrum directly gives a slope steep
    enough to mean something, and is faster than looping in Python.
    """
    spec = np.fft.rfft(x)
    freqs = np.fft.rfftfreq(len(x), 1 / SR)
    f = np.maximum(freqs, 1e-6)
    h = np.ones_like(f)
    if hi:
        h *= 1.0 / np.sqrt(1.0 + (f / hi) ** (2 * order))
    if lo:
        h *= 1.0 / np.sqrt(1.0 + (lo / f) ** (2 * order))
    return np.fft.irfft(spec * h, n=len(x))


def modal(dur, modes, strike=0.0, strike_tau=0.004, strike_band=(900, 5000)):
    """Modes is a list of (freq, tau, amp).

    The strike is a *band* of noise, not everything above a cutoff. Open-ended at the top
    it runs to Nyquist, which is far more energy than the modes carry, and it turned every
    clack into a hiss.
    """
    times = t(dur)
    out = np.zeros_like(times)
    for freq, tau, amp in modes:
        out += partial(times, freq, tau, amp, rng.uniform(0, 2 * np.pi))
    if strike:
        out += strike * noise(times, strike_tau, *strike_band)
    return out


def blip(dur, f0, f1, tau, shape="sine"):
    """A short tone that slides from f0 to f1 — the UI vocabulary."""
    times = t(dur)
    sweep = np.linspace(f0, f1, len(times))
    phase = 2 * np.pi * np.cumsum(sweep) / SR
    wave_ = np.sin(phase)
    if shape == "soft":
        wave_ = np.sin(phase) * 0.8 + np.sin(2 * phase) * 0.2
    return wave_ * decay(times, tau)


def attack(x, ms=1.5):
    """Ease the first moment in. A hard start is an audible click of its own."""
    n = min(len(x), int(SR * ms / 1000))
    if n > 1:
        x = x.copy()
        x[:n] *= np.linspace(0.0, 1.0, n)
    return x


def tail(x, ms=6.0):
    """And ease the last moment out, so the file cannot end on a step."""
    n = min(len(x), int(SR * ms / 1000))
    if n > 1:
        x = x.copy()
        x[-n:] *= np.linspace(1.0, 0.0, n)
    return x


def trim(x, floor_db=-60.0):
    """Cut the silence off the end.

    Most of these decay to nothing well before their nominal length — a clack is audible
    for 40 ms of its 110. The tail costs nothing to store but it does hold a voice open in
    the mixer, and the pool is what limits how many dice can rattle at once.
    """
    floor = 10 ** (floor_db / 20) * np.max(np.abs(x))
    loud = np.flatnonzero(np.abs(x) > floor)
    return x[:loud[-1] + 1] if len(loud) else x


def finish(x, peak_db=-3.0):
    x = tail(trim(x))
    x = attack(x)
    top = np.max(np.abs(x))
    if top > 0:
        x = x / top * (10 ** (peak_db / 20))
    return x


# ---------------------------------------------------------------------------
# The sounds. Peak is where each one sits relative to the others: a die landing
# should not be as loud as the whole board being thrown.
# ---------------------------------------------------------------------------

def die_hit(seed_shift):
    """A die striking something. Four variants so a rattle does not machine-gun."""
    base = 1350 * (1.0 + 0.11 * seed_shift)
    return modal(0.11, [
        (base,        0.028, 1.00),
        (base * 1.63, 0.020, 0.62),
        (base * 2.41, 0.014, 0.38),
        (base * 3.77, 0.009, 0.20),
        (base * 0.51, 0.045, 0.30),      # the low body, which gives it size
    ], strike=0.55, strike_band=(base * 0.7, base * 4.5))


def die_land():
    """The settle at the end of a roll: lower, duller, longer."""
    return modal(0.20, [
        (520,  0.055, 1.00),
        (770,  0.040, 0.55),
        (1180, 0.026, 0.30),
        (280,  0.080, 0.45),
    ], strike=0.35, strike_tau=0.008, strike_band=(220, 1800))


def die_roll():
    """Rolled where it stands — from the menu, or the R key.

    A rattle, not a throw: the die never goes anywhere, so this is four soft strikes
    close together, thinning out as it settles, over a light bed of noise. Deliberately
    smaller than throw_all, which is the same idea for the whole board at once.
    """
    times = t(0.34)
    out = np.zeros_like(times)
    for k, offset in enumerate((0.0, 0.075, 0.145, 0.225)):
        start = int(SR * (offset + rng.uniform(0.0, 0.012)))
        hit = die_hit(k) * (0.85 - 0.16 * k)
        end = min(len(out), start + len(hit))
        out[start:end] += hit[:end - start]
    bed = band(rng.normal(0, 1, len(times)), 250, 1600) * decay(times, 0.12) * 0.22
    return out + bed


def die_throw():
    """Release. A short airy push, no pitch — it is a gesture, not a note."""
    times = t(0.22)
    swell = np.sin(np.pi * np.linspace(0, 1, len(times))) ** 1.6
    return band(rng.normal(0, 1, len(times)), 300, 2200) * swell


def throw_all():
    """Space. The board takes a knock and everything goes at once."""
    times = t(0.45)
    rumble = (partial(times, 78, 0.16, 1.0) + partial(times, 116, 0.11, 0.6))
    air = band(rng.normal(0, 1, len(times)), 200, 2400) * decay(times, 0.13) * 0.8
    clatter = np.zeros_like(times)
    for k in range(5):                    # a handful of dice hitting, spread out
        start = int(SR * (0.02 + 0.055 * k + rng.uniform(0, 0.02)))
        hit = die_hit(k) * 0.5
        end = min(len(clatter), start + len(hit))
        clatter[start:end] += hit[:end - start]
    return rumble + air + clatter


def respawn():
    """Everything gathers back to the middle."""
    times = t(0.30)
    sweep = band(rng.normal(0, 1, len(times)), 400, 2600) * decay(times, 0.10) * 0.6
    return sweep + blip(0.30, 300, 620, 0.10) * 0.7


def ui_click():
    return modal(0.045, [
        (2400, 0.010, 1.00),
        (3600, 0.006, 0.45),
    ], strike=0.30, strike_tau=0.002, strike_band=(1800, 5500))


def ui_open():
    return blip(0.13, 420, 700, 0.055, "soft")


def ui_close():
    return blip(0.13, 700, 420, 0.055, "soft")


def spawn():
    """A die arrives on the board: a soft set-down with a small lift under it."""
    times = t(0.20)
    thud = modal(0.20, [(300, 0.045, 1.0), (450, 0.030, 0.5)], strike=0.25,
                 strike_tau=0.006, strike_band=(180, 1400))
    return thud + blip(0.20, 520, 780, 0.06) * 0.35


def delete():
    return blip(0.18, 700, 260, 0.06, "soft") + \
        band(rng.normal(0, 1, len(t(0.18))), 250, 1600) * decay(t(0.18), 0.05) * 0.35


def link():
    """Two dice become one d100. Two notes, upward, the second the stronger."""
    a = np.concatenate([blip(0.09, 660, 660, 0.05) * 0.7, np.zeros(int(SR * 0.02))])
    b = blip(0.20, 990, 990, 0.075)
    out = np.zeros(max(len(a), len(a) - int(SR * 0.02) + len(b)))
    out[:len(a)] += a
    at = len(a) - int(SR * 0.02)
    out[at:at + len(b)] += b
    return out


def unlink():
    a = np.concatenate([blip(0.09, 990, 990, 0.05) * 0.7, np.zeros(int(SR * 0.02))])
    b = blip(0.20, 660, 660, 0.075)
    out = np.zeros(max(len(a), len(a) - int(SR * 0.02) + len(b)))
    out[:len(a)] += a
    at = len(a) - int(SR * 0.02)
    out[at:at + len(b)] += b
    return out


def theme():
    """Picking a colour. Deliberately the quietest thing in the set."""
    return blip(0.10, 880, 1180, 0.04, "soft")


SOUNDS = [
    ("die_hit_0",  lambda: die_hit(0), -4.0),
    ("die_hit_1",  lambda: die_hit(1), -4.0),
    ("die_hit_2",  lambda: die_hit(2), -4.0),
    ("die_hit_3",  lambda: die_hit(3), -4.0),
    ("die_land",   die_land,           -5.0),
    ("die_roll",   die_roll,           -5.0),
    ("die_throw",  die_throw,          -9.0),
    ("throw_all",  throw_all,          -2.0),
    ("respawn",    respawn,            -7.0),
    ("ui_click",   ui_click,           -11.0),
    ("ui_open",    ui_open,            -10.0),
    ("ui_close",   ui_close,           -10.0),
    ("spawn",      spawn,              -6.0),
    ("delete",     delete,             -7.0),
    ("link",       link,               -7.0),
    ("unlink",     unlink,             -7.0),
    ("theme",      theme,              -13.0),
]


def write_wav(path, samples):
    data = np.clip(samples, -1.0, 1.0)
    pcm = (data * 32767).astype("<i2")
    with wave.open(path, "wb") as f:
        f.setnchannels(1)
        f.setsampwidth(2)
        f.setframerate(SR)
        f.writeframes(pcm.tobytes())


def centroid(x):
    """Spectral centroid in Hz — one number for 'how bright is this'."""
    spec = np.abs(np.fft.rfft(x))
    freqs = np.fft.rfftfreq(len(x), 1 / SR)
    total = spec.sum()
    return float((spec * freqs).sum() / total) if total else 0.0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="write the WAVs")
    ap.add_argument("--preview", action="store_true",
                    help="also write out/preview.png")
    args = ap.parse_args()

    out = os.path.normpath(OUT)
    if args.write:
        os.makedirs(out, exist_ok=True)

    rendered = []
    print(f"{'sound':<12} {'ms':>6} {'peak dBFS':>10} {'rms dBFS':>9} {'centroid':>9}")
    for name, make, peak_db in SOUNDS:
        # crc32, not hash(): Python randomises string hashing per process, so seeding
        # from it gave a different set of files on every run. Everything generated in this
        # repository is meant to come out byte-identical twice running.
        globals()["rng"] = np.random.default_rng(zlib.crc32(name.encode()))
        x = finish(make(), peak_db)
        rendered.append((name, x))
        rms = 20 * np.log10(np.sqrt(np.mean(x ** 2)) + 1e-12)
        print(f"{name:<12} {1000 * len(x) / SR:6.0f} {20 * np.log10(np.max(np.abs(x))):10.1f}"
              f" {rms:9.1f} {centroid(x):8.0f}Hz")
        if args.write:
            write_wav(os.path.join(out, name + ".wav"), x)

    if args.write:
        print(f"\nwrote {len(rendered)} files to {out}")
    else:
        print("\n(dry run — pass --write to save)")

    if args.preview:
        preview(rendered)
    return 0


def preview(rendered):
    """One strip per sound: the waveform, and an STFT beside it.

    Drawn with PIL rather than matplotlib — numpy and PIL are what the other tools in
    this repository already need, and a preview is not worth a third dependency.
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        print("Pillow not installed; skipping preview", file=sys.stderr)
        return

    here = os.path.join(os.path.dirname(__file__), "out")
    os.makedirs(here, exist_ok=True)

    label_w, wave_w, spec_w, row_h, pad = 92, 300, 300, 54, 6
    width = label_w + wave_w + spec_w + pad * 3
    height = row_h * len(rendered) + pad
    img = Image.new("RGB", (width, height), (32, 35, 43))
    draw = ImageDraw.Draw(img)

    # Longest sound sets the time scale, so the strips are comparable to each other.
    longest = max(len(x) for _, x in rendered)

    for i, (name, x) in enumerate(rendered):
        top = pad + i * row_h
        draw.text((6, top + row_h // 2 - 10), name, fill=(230, 232, 242))

        # --- waveform, min/max per column ---
        x0 = label_w + pad
        cols = int(round(wave_w * len(x) / longest))
        mid = top + (row_h - 12) // 2
        half = (row_h - 18) // 2
        draw.line([(x0, mid), (x0 + wave_w, mid)], fill=(58, 64, 83))
        if cols > 1:
            edges = np.linspace(0, len(x), cols + 1).astype(int)
            for c in range(cols):
                seg = x[edges[c]:edges[c + 1]]
                if not len(seg):
                    continue
                draw.line([(x0 + c, mid - int(seg.max() * half)),
                           (x0 + c, mid - int(seg.min() * half))], fill=(127, 208, 160))

        # --- spectrogram ---
        s0 = label_w + wave_w + pad * 2
        frame, hop = 512, 160
        if len(x) > frame:
            n = 1 + (len(x) - frame) // hop
            win = np.hanning(frame)
            mag = np.abs(np.fft.rfft(
                np.stack([x[k * hop:k * hop + frame] * win for k in range(n)]), axis=1))
            db = 20 * np.log10(mag + 1e-9)
            db = np.clip((db - db.max() + 60) / 60, 0, 1)      # 60 dB of range
            bins = int(frame / 2 * 8000 / (SR / 2))            # show 0..8 kHz
            tile = db[:, :bins].T[::-1]
            colour = np.stack([
                np.clip(tile * 2.4 - 0.35, 0, 1),
                np.clip(tile * 1.7 - 0.55, 0, 1),
                np.clip(tile * 2.0 - 0.10, 0, 1) * 0.8,
            ], axis=-1)
            strip = Image.fromarray((colour * 255).astype("uint8"))
            wide = max(1, int(round(spec_w * len(x) / longest)))
            img.paste(strip.resize((wide, row_h - 14), Image.BILINEAR), (s0, top + 4))

    img.save(os.path.join(here, "preview.png"))
    print("preview ->", os.path.join(here, "preview.png"))


if __name__ == "__main__":
    sys.exit(main())
